### ISSUE TITLE
Adjust TALENTS profile layout

### ISSUE THREAD

**Issue by marcelirodriguez** [fablabbcn/DDMP-web#1]
@hacknug 

- [x] La idea sería que los botones de "view project" y "visit web" se puedan personalizar los links y también el texto del botón. En cuanto al estilo, cuando haces hover, que se rellene con el color amarillo de la sección.

- [x] Los botones con enlaces a las redes sociales de la persona, solo deberán aparecer si añadimos los enlaces correspondientes.

- [x] Los botones de SHARE para redes sociales, sería cool que se mantengan siempre visibles en la columna derecha mientras haces scroll.

- [x] La nueva sección que está debajo de la foto del proyecto, sería para añadir siempre una descripción super breve explicando el proyecto.

- [x] Estaría cool si podemos convertir la primera foto en slider para que se pueda hacer un overview del proyecto rápidamente sin tener que hacer mucho scroll. _Si esto es complicado, o tardará mucho tiempo, podemos obviarlo de momento._

- [x] Ahora la idea es poner siempre la foto de la persona más pequeña donde la ves a la izquierda, y a la derecha en grande una foto del proyecto.

**AQUÍ VA EL MOCKUP:**

[DDMP_WEB_TALENTS.pdf](https://github.com/fablabbcn/DDMP-web/files/2966268/DDMP_WEB_TALENTS.pdf)

**AQUÍ VAN LOS ASSETS:**

https://drive.google.com/open?id=1kZOCsWJzC6yu6zj4ZlRGszCUJvcWtJ5o

**Comment by hacknug** [comment]
> * Los botones de SHARE para redes sociales, sería cool que se mantengan siempre visibles en la columna derecha mientras haces scroll.

Para que se queden stickies tocará rehacer el layout. De momento tenemos botones de compartir que hablamos en la reunión así que lo marco como completado.

> * Ahora la idea es poner siempre la foto de la persona más pequeña donde la ves a la izquierda, y a la derecha en grande una foto del proyecto.

Usamos la Featured Image para el listado del archivo y para la ficha del talento. La galería que he añadido (_Featured Image (Alternative)_) servirá para mostrar una imagen destacada distinta a la del archivo, un video (como en About una vez esté listo), o un slider (en caso de seleccionar más de una).
