### ISSUE TITLE
Add FabLab Budapest in the HOME

### ISSUE THREAD

**Issue by marcelirodriguez** [fablabbcn/DDMP-web#12]
@hacknug 
![Captura de pantalla 2019-04-01 a las 18 05 04](https://user-images.githubusercontent.com/40209195/55342265-b508c300-54a8-11e9-9f07-213e6053b67f.png)

En esta sección, debemos añadir como nuevo partner: *FABLAB BUDAPEST*

Y el texto que aparece cuando haces click sería:

FabLab's Budapest motto is an individual Fab Lab in the downtown of Budapest, Hungary. In cooperation of the Asimov Foundation we host the first BioHack space in the country. Tiny but growing and open for everybody from kids to crazy scientists!

**Comment by hacknug** [comment]
@marcelirodriguez esto lo controláis vosotros desde la página **Home**.
