### ISSUE TITLE
Fix events layout

### ISSUE THREAD

**Issue by marcelirodriguez** [fablabbcn/DDMP-web#14]
@hacknug has visto como quedaron los eventos al hacer el update?

Recuerdo que estuvimos haciendo la migración de todo el contenido para que cuando actualizaras el layout apareciera bien.

Sabes que habrá pasado? Es super importante solucionar esto cuando antes, please.

Gracias.

**Comment by marcelirodriguez** [comment]
Hola @hacknug necesitamos resolver esto urgentemente, por favor. Avísame cualquier cosa que necesites. Gracias.

**Comment by hacknug** [comment]
@marcelirodriguez cierro esto que en principio ya quedó corregido con el último update hace días.
