### ISSUE TITLE
Issues with the forms

### ISSUE THREAD

**Issue by marcelirodriguez** [fablabbcn/DDMP-web#16]
@hacknug 

### **GENERAL - APPLIES TO ALL FORMS:**

- [x] In general are all login forms cut
![Screen Shot 2019-05-17 at 4 21 37 PM](https://user-images.githubusercontent.com/40209195/57934405-f3730980-78bf-11e9-9754-14795ef9768e.png)

- [x]  once you scroll down you cannot scroll up anymore to go back to the beginning of the forms

- [x] Is not possible to submit any blogpost, nothing happens if I click "submit" or the "submit" button is not existing

- [x] What does the "SIGN IN" button means? What should it do? Should it be "SUBMIT", maybe?
![Screen Shot 2019-05-17 at 4 21 37 PM](https://user-images.githubusercontent.com/40209195/57934405-f3730980-78bf-11e9-9754-14795ef9768e.png)

### **TALENTS FORM:**

- [x] The buttons to reshare the talent are not shown as buttons in the login form, so you don't understand what this is 

- [x] Cannot upload photos
![unnamed](https://user-images.githubusercontent.com/40209195/57934680-80b65e00-78c0-11e9-90fa-1ab1a40a4e79.png)

- [x] Could you please explain us which content goes in the following section, so we can change the titles so they're more explicit for the platform members to plubish content:
![Screen Shot 2019-05-17 at 4 35 29 PM](https://user-images.githubusercontent.com/40209195/57935489-30d89680-78c2-11e9-9c33-7535c006c719.png)

- [x] What would these buttons be?
![Screen Shot 2019-05-17 at 4 36 34 PM](https://user-images.githubusercontent.com/40209195/57935506-3cc45880-78c2-11e9-98b5-1a6d2d1369ac.png)

### **BLOG FORM:**

- [x] There's an important bug
![Screen Shot 2019-05-17 at 4 26 35 PM](https://user-images.githubusercontent.com/40209195/57934738-a17eb380-78c0-11e9-9bd5-383b38577809.png)

- [x] I cannot submit - if I want to create a new blogpost I click "add blogpost" - I fill in - and when I want to submit, id does not give me the submit option but just "login" which I cannot click on either

### **EVENTS FORM:**

- [x] The login form seems to be good, although I cannot submit again

### **RESOURCES FORM:**

- [x] Is not working at all

**Comment by hacknug** [comment]
- `Cannot upload photos` debería revisarlo quien lleve el tema del servidor
