### ISSUE TITLE
Other important bugs

### ISSUE THREAD

**Issue by marcelirodriguez** [fablabbcn/DDMP-web#17]
@hacknug 
- [x] The published events until now do not show the address and dates anymore
- [x] Events are not showing the corresponding image
![Screen Shot 2019-05-17 at 4 32 00 PM](https://user-images.githubusercontent.com/40209195/57935091-51542100-78c1-11e9-819c-d10ebe19b057.png)

- [x] There's a problem with the talents archive, the first row is looking fine but the second one is like streched
![Screen Shot 2019-05-17 at 4 40 15 PM](https://user-images.githubusercontent.com/40209195/57935677-a5abd080-78c2-11e9-96a8-de14f617cb70.png)
![Screen Shot 2019-05-17 at 4 40 24 PM](https://user-images.githubusercontent.com/40209195/57935680-a7759400-78c2-11e9-946b-17f21ec4ccd2.png)

- [x] Doubt: how do we use the shortcut for the rounded button in the posts?

**Comment by hacknug** [comment]
@marcelirodriguez puedes pasarme el link que os genera esta página para revisar lo de Talents? https://www.whatsmybrowser.org/

**Comment by marcelirodriguez** [comment]
@hacknug www.whatsmybrowser.org/b/7NZ4UTH

**Comment by hacknug** [comment]
No puedo reproducirlo. ¿Sigue ocurriendo en vuestro ordenador?

<img width="2608" alt="Captura de pantalla 2019-05-29 a las 14 48 58" src="https://user-images.githubusercontent.com/1107521/58558366-ea1f6080-8220-11e9-80dd-56847e3956d6.png">
