### ISSUE TITLE
Other fixes

### ISSUE THREAD

**Issue by marcelirodriguez** [fablabbcn/DDMP-web#4]
@hacknug 

**GENERAL**

- [x] Intext Links (Underline and use sections primary colour when hover)
- [x] Add "share on social media" buttons on: **talent profiles**, **news pages** and **blog posts**
- [x] Remove "search" for now

**EVENTS PAGE**
- [x] Teach us how to miagrate the content: https://streamable.com/q6uk4
- [x] Cronological order newest to olderst on events menu
- [x] 2019 before 2018 on events menu
- [x] Pagination

**NEWS PAGE**
- [x] Fix broken clause

**Comment by marcelirodriguez** [comment]
Hola @hacknug nos podrías comentar brevemente cómo hacer la migración del contenido de los eventos? Es que debemos tener esto listo y online para el jueves. Muchas gracias!

**Comment by hacknug** [comment]
@marcelirodriguez necesitaría que ampliaseis el espacio disponible para la web o no podré hacer una copia de seguridad antes de actualizar. Si no podéis hacerlo actualizo tal cual (no creo que ocurra nada pero siempre prefiero hacerla por si las moscas…).

```
Out of disk space. Unable to write content to file.
```

**Comment by marcelirodriguez** [comment]
Hecho :) ahora tenemos 5GB, es suficiente? @hacknug

**Comment by hacknug** [comment]
@marcelirodriguez yes!

**Comment by hacknug** [comment]
@marcelirodriguez Ya que estamos, sabes si podemos también cambiar la versión de PHP del servidor?

**Comment by marcelirodriguez** [comment]
Qué versión necesitas? se lo comento a la gente del server @hacknug

**Comment by hacknug** [comment]
@marcelirodriguez a poder ser PHP 7.2 o 7.3 si no hay nada que de problemas. Así ganamos en performance y seguridad y podemos ir actualizando todo sin preocuparnos durante un tiempo.

**Comment by marcelirodriguez** [comment]
Cool, se los comento a ver. Gracias!

**Comment by marcelirodriguez** [comment]
Hola @hacknug, necesito hablar contigo urgente? puedes responderme por slack, please? gracias.

**Comment by marcelirodriguez** [comment]
@hacknug podrías revisar por qué aparece caída la página ahora? Please

Además, me comenta Lisa que no salen publicados todos los talents que subió.

Y lo demás que falta cuando podríamos tenerlo?

Necesitamos tener todo online ya, por favor.

Gracias!
