### ISSUE TITLE
Fix post headings capitalization

### ISSUE THREAD

**Issue by hacknug** [fablabbcn/DDMP-web#6]
@Katearmstrong4 @marcelirodriguez which posts needed this fix?

**Comment by marcelirodriguez** [comment]
This should be for all of the headings, in the menu, blog posts, talents, news, sections titles, sub-categories in the menu...

**Comment by hacknug** [comment]
- [x] menu items
- [x] single posts
- [x] post archives
- [x] sections titles

**Comment by hacknug** [comment]
Closing this as it should work fine once I update the live site. Let me know if I missed anything once you take a look at it.
